version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: sapid
      POSTGRES_PASSWORD: sapid
      POSTGRES_DB: sapid
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

  chroma:
    image: chroma/chroma:latest
    environment:
      IS_PERSISTENT: "TRUE"
    volumes:
      - chroma_data:/chroma
    healthcheck:
      test: ["CMD", "curl", "-f", "http://chroma:8000/heartbeat"]
      interval: 10s
      timeout: 5s
      retries: 5

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    command: ["ollama", "serve"]
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://ollama:11434/api/tags"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: backend/docker
    depends_on:
      - postgres
      - chroma
      - ollama
    environment:
      POSTGRES_URL: postgresql://sapid:sapid@postgres:5432/sapid
      CHROMA_URL: http://chroma:8000
      OLLAMA_URL: http://ollama:11434
      OLLAMA_CHAT_MODEL: tinyllama:latest
      OLLAMA_EMBED_MODEL: nomic-embed-text
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/app
      - ./frontend:/frontend

  nginx:
    image: nginx:alpine
    depends_on:
      - frontend-build
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
    ports:
      - "3000:80"

  frontend-build:
    image: node:20-alpine
    working_dir: /workspace
    volumes: [ "./frontend:/workspace" ]
    command: ["sh","-c","npm ci && npm run build"]
    profiles: [ "build" ]


  whisper:
    build:
      context: ./docker/voice
      dockerfile: Dockerfile.whisper
    ports:
      - "9000:9000"
    profiles:
      - voice

  tts:
    build:
      context: ./docker/voice
      dockerfile: Dockerfile.tts
    ports:
      - "9001:9001"
    profiles:
      - voice


volumes:
  postgres_data: {}
  chroma_data: {}
  ollama_models: {}
